#!/bin/bash

function atoab() {

    optspec s,n:
    [ -z ${opts[n]} ] &&  opts[n]=0

    local inum=$(( ${args[@]} ))
    local bnum=

    while (( inum )); do
      bnum=$(( inum % 2 ))${bnum}
      inum=$(( inum >> 1))
    done

    local nd=$(( ${opts[n]} - ${#bnum} ))

    if [ ${nd} -gt 0 ]; then
      for nd in $(seq ${nd}); do
        bnum=0${bnum}
      done
    fi

    if (( ${opts[s]} )); then
      bnum=$(echo 000${bnum} |
              sed -r  's/^0{0,3}((.{4})*)$/\1/
                       s/(.{4})/\1 /g
                       s/ $//')
    fi

    echo ${bnum}

 }


[ ${0##*/} = atoab ] &&  atoab ${@}

