#!/bin/bash


atoab ()
{
   optspec s:,n:;
   local onum inum=$(( ${args[@]} ));

   for onum in ${!opts[@]}; do
     if [ _"${opts[${onum}]}" = _0 ]; then
       unset opts[${onum}];
     fi;
   done;
   onum=;

   case ${inum} in
     0)
       onum=0 ;;

     -[1-9]*([0-9]))
       echo 1>&2 'negative :(' ;
       return 1 ;;

     *(0)[1-9]*([0-9]))
       while (( inum >= 1 )); do
         onum=$(( ${inum} % 2 ))${onum};
         let inum/=2;
       done ;;

     *)
       echo 1>&2 'garbage :(' ;
       return 2 ;;
   esac;

   inum=$(( ( ${opts[n]:-0} >= ${#onum} ) ? ${opts[n]:-${#onum}} : ${#onum} ));
   let inum+=$(( (${inum} % ${opts[s]:-${inum}}) % ${opts[s]:-1} ));
   let inum-=${#onum};

   if (( inum > 0 )); then
     inum="$(eval "echo {1..${inum}}")";
     onum=${inum//+([0-9])?( )/0}${onum};
   fi;

   if [ -n "${opts[s]}" ]; then
     onum="$( echo ${onum} | sed -r "{:0; s/([^ ]+)([01]{${opts[s]}})/\1 \2/g; t0; }" )";
   fi;

   echo "${onum}";
}


[[ $0 != *atoab* ]] ||  eval "atoab $@"
