#!/bin/bash
shopt -qs expand_aliases


alias objdump='__objdump_wrapper '
alias lobjdump='__objdump_wrapper --LESS '
alias __objdump_wrapper='__objdump_wrapper_fn '

__objdump_wrapper_fn ()
{
   local _item _less _switches _args;

   for _item in $@;  do
     case $_item in
       --LESS)   _less="less -F";;
       -?*)      _switches="$_item $_switches";;
       *)        _args="$_item $_args";;
     esac;
   done;

   eval "$(which objdump) ${_switches:- -dr} $_args" | ${_less:- cat};
}


[[ $0 == *lobjdump* ]] &&  eval "lobjdump $@"
