#!/bin/bash

alias optspec &>/dev/null ||  source $(which optspec)


function pnchars() {

   optspec c:
   args=$(( ${args[@]} ))
   local char=${opts[c]:-:}

   if (( args )); then
     local n str
     for n in $(seq ${args}); do
       str="${char}${str}"
     done

     echo ${str}
     history -s $(echo ${str})
     history -s "pnchars ${@}"
   fi

 }


[ ${0##*/} = pnchars ] &&  pnchars ${@}

