#!/bin/bash

_whichs ()
 {
   local _path="${PATH//\/mnt+([^:]):}";
   local _arg="${*/#-*}";
   local _redir=/dev/null;
   local _scratch="${*/#!(-?*)}";
   local _cmd=-;

   case "${_scratch/#*( )}" in
     *E*) _redir=/proc/self/fd/2 ;;&
     *i*) _cmd+=i ;;&
     *r*) _cmd+=regex ;;
     *w*) _cmd+=whole ;&
     *) _cmd+=name ;;
   esac;

   _scratch="$( for _path in ${_path//:/ }; do
                   find "${_path}" ${_cmd} "${_arg}" {err}<>${_redir} 2>&${err} ;
                 done; )"
   for _path in ${_scratch}; do
     echo -e "${_path##*/}\\t  ${_path%/*}";
   done;

   _path="$(enable -p)";
   for _scratch in ${_path//enable }; do
     [[ ${_scratch} == ${_arg} ]] && echo -e "${_scratch}\\t  (shell builtin)";
   done;

   _path="$(declare -F)";
   for _scratch in ${_path//declare -f }; do
     [[ ${_scratch} == ${_arg} ]] && echo -e "${_scratch}\\t (shell function)";
   done;

   _path="$( alias | sed -r 's/^alias (([^\\=]|\\=)+)=.*/\1/' )";
   for _scratch in ${_path}; do
     [[ ${_scratch} == ${_arg} ]] && echo -e "${_scratch}\\t (shell alias)";
   done;
 }


alias whichs='trap "set +fT; [ -z "${-//[^fT]}" ] || set -${-//[^fT]}; trap RETURN;" RETURN; set -fT; _whichs '
alias _whichs='_whichs '

# [[ $0 != *whichs* ]] ||  eval "whichs $@"

# whichs()
#    [[ x$BASHOPTS == *extglob* ]] &&
#       { local _extglob=s;     }  ||
#       { local _extglob=u;
#         shopt -qs extglob;    };
#
#    local _switches=" ${@/#!(-?*)} ";
#       _switches="${_switches// /:}";
#    local _match;
#    [ "x${_switches/:i:}" != "x$_switches" ] &&
#       { _match=i;                        };
#    [ "x${_switches/:r:}" != "x$_switches" ] &&
#       { _match="-${_match}regex";        }  ||
#       { _match="-${_match}name";         };
#    local _args="${@@Q}";
#       _args="${_args//[\']-[^\']*([^\' ])[\']}";
#       _args="${_args##+( )}";
#       _args="${_args%%+( )}";
#    local _bindir;
#    local _cmd="$_match ${_args// / -o $_match } 2>/dev/null";
#
#    [ "x${_extglob}" == "xu" ] &&
#       { shopt -qu extglob; };
#
#    for _bindir in ${PATH//:/ }; do
#      eval "find $_bindir $_cmd" &
#    done |
#      xargs -rd\\\\n\n echo -e;
# }
